name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my_ml_model .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


